[parse]
net_name = "doclayout_yolo"
framework = "pytorch"
frame_version = "1.9"
inputs = [1, 1280, 992, 3]
inputs_layout = "NHWC"
pre_method = "resize"
pre_scale = [255.0, 255.0, 255.0]
pre_mean = [0.0, 0.0, 0.0]
channel_swap = [0, 1, 2]
network = "fmodel/doclayout_yolo_docstructbench_imgsz1280_2501.pt"
jr_path = "../3_deploy/modelzoo/yolov10/imodel/8/"

[optimize]
target = "BUYI"
json = "../3_deploy/modelzoo/yolov10/imodel/8/doclayout_yolo_parsed.json"
raw = "../3_deploy/modelzoo/yolov10/imodel/8/doclayout_yolo_parsed.raw"
jr_path = "../3_deploy/modelzoo/yolov10/imodel/8/"

[quantize]
forward_mode = "image"
saturation = "kld"
forward_dir = "./qtset/pdf_imgs"
forward_list = "./qtset/pdf_imgs.txt "
batch = 1
bits = 8
json = "../3_deploy/modelzoo/yolov10/imodel/8/doclayout_yolo_optimized.json"
raw = "../3_deploy/modelzoo/yolov10/imodel/8/doclayout_yolo_optimized.raw"
jr_path = "../3_deploy/modelzoo/yolov10/imodel/8/"
per = "channel"
target = "buyi"

[adapt]
target = "BUYI"
json = "../3_deploy/modelzoo/yolov10/imodel/8/doclayout_yolo_quantized.json"
raw = "../3_deploy/modelzoo/yolov10/imodel/8/doclayout_yolo_quantized.raw"
jr_path = "../3_deploy/modelzoo/yolov10/imodel/8/"
# pass_on = "customop.ImageMakePass,customop.DetPostPass"
# custom_config = "config/customop/yolov10.toml"

[generate]
json = "../3_deploy/modelzoo/yolov10/imodel/8/doclayout_yolo_adapted.json"
raw = "../3_deploy/modelzoo/yolov10/imodel/8/doclayout_yolo_adapted.raw"
jr_path = "../3_deploy/modelzoo/yolov10/imodel/8/"

[run]
log_time = true
log_io = true
dump_format = "SFB"
json = "../3_deploy/modelzoo/yolov10/imodel/8/doclayout_yolo_BY.json"
raw = "../3_deploy/modelzoo/yolov10/imodel/8/doclayout_yolo_BY.raw"
input = "./qtset/pdf_imgs/page_5.png"
backends = "Host"
